openapi: 3.0.0
info:
  version: 1.0.0
  title: 'Hello, World'
  description: hello world
servers:
  - url: /node/executive/
    description: Hello world
tags:
  - name: KO Endpoints
    description: Hello World Endpoints
paths:
  /process:
    post:
      tags:
        - KO Endpoints
      description: process.
      operationId: process
      requestBody:
        description: inputs
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/input'
      responses:
        '200':
          description: response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/output'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
      x-kgrid-activation:
        artifact: 'src/index.js'
        adapter: 'JAVASCRIPT'
        entry: 'process'
components:
  schemas:
    input:
      required:
        - name
        - height
        - weight
      properties:
        name:
          type: string
          x-kgrid-label: 'Please enter your name'
          x-kgrid-unit: ''
          example: Bob
        height:
          type: number
          example: 1.7
        weight:
          type: number
          example: 72.5
    output:
      required:
        - result
      properties:
        result:
          type: object
    error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
