openapi: 3.0.2
info:
  version: 1.0.0
  title: 'Hello, KGrid'
  description: hello KGrid
servers:
  - url: /hello/KGrid
    description: Hello KGrid
tags:
  - name: KO Endpoints
    description: Hello KGrid Endpoints
paths:
  /welcome:
    post:
      tags:
        - KO Endpoints
      description: Welcome.
      operationId: welcome
      requestBody:
        description: inputs
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/input'
      responses:
        '200':
          description: response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/output'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
      x-kgrid-activation:
        artifact: 'src/index.js'
        adapter: 'JAVASCRIPT'
        entry: 'welcome'
components:
  schemas:
    input:
      required:
        - name
      properties:
        name:
          type: string
          x-kgrid-label: 'Please enter your name'
          x-kgrid-unit: ''
          example: Bob
    output:
      required:
        - result
      properties:
        result:
          type: object
    error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
